oka_notifier_server_messages_list:
    methods: GET
    path: /{version}/{protocol}/messages
    controller: Oka\Notifier\ServerBundle\Controller\MessageController::list

oka_notifier_server_messages_read:
    methods: GET
    path: /{version}/{protocol}/messages/{id}
    controller: Oka\Notifier\ServerBundle\Controller\MessageController::read

oka_notifier_server_messages_delete:
    methods: DELETE
    path: /{version}/{protocol}/messages/{id}
    controller: Oka\Notifier\ServerBundle\Controller\MessageController::delete
