oka_notifier_server_send_reports_list:
    methods: GET
    path: /{version}/{protocol}/send-reports
    controller: Oka\Notifier\ServerBundle\Controller\SendReportController::list

oka_notifier_server_send_reports_read:
    methods: GET
    path: /{version}/{protocol}/send-reports/{id}
    controller: Oka\Notifier\ServerBundle\Controller\SendReportController::read
